spring.application.name=servicedesk-pro
spring.datasource.url=jdbc:mysql://localhost:3306/servicedesk_db
spring.datasource.username=abdulsuban
spring.datasource.password=Subbu@2907

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true